package com.flowprototype.backend.flow.model;

/**
 * Local mock of Constants.XmfIxservType.IxtDisplayType.
 * Names and database values mirror ixserv without introducing a module dependency.
 */
public enum IxtDisplayType {
    DISPTYPE_NONE(0),
    DISPTYPE_REPORT(1),
    DISPTYPE_CUMREP(2),
    DISPTYPE_CUMREP_COMPACT(100),
    DISPTYPE_TEXT(3),
    DISPTYPE_CUMREP_TEXT(20),
    DISPTYPE_REPORT_MIBI_STRUCTURED(21),
    DISPTYPE_CUMREP_MIBI_STRUCTURED(19),
    DISPTYPE_URL(5),
    DISPTYPE_ARCHIVE(6),
    DISPTYPE_PICT(7),
    DISPTYPE_CUMFORM(10),
    DISPTYPE_PDFFORM(11),
    DISPTYPE_DISCHARGEREPORT(12),
    DISPTYPE_REPORT_MULTIPART(15),
    DISPTYPE_EXTLINK(16),
    DISPTYPE_WEBDAV_DOCUMENT(22),
    DISPTYPE_HEYEX_COMPLEX(23),
    DISPTYPE_MPPS(24),
    DISPTYPE_FORM(25),
    DISPTYPE_APP_WARD_OVERVIEW(27),
    DISPTYPE_APP_FAC_OVERVIEW(28),
    DISPTYPE_APP_PAT_OVERVIEW(29),
    DISPTYPE_APP_DETAIL(30),
    DISPTYPE_DASH_FAC(31),
    DISPTYPE_DASH_FLOOR(32),
    DISPTYPE_PAT_CASE_DETAIL(33),
    DISPTYPE_PAT_DETAIL(34),
    DISPTYPE_SAMPLE_ORDERLIST(35),
    DISPTYPE_SAMPLE_SAMPLELIST(36),
    DISPTYPE_SAMPLE_SAMPLELIST_UNSCANNED(82),
    DISPTYPE_CONF_DETAIL(37),
    DISPTYPE_CONF_OVERVIEW(38),
    DISPTYPE_MPI_PAT_DETAILS(39),
    DISPTYPE_MPI_PAT_LIST(40),
    DISPTYPE_STATISTICS_OVERVIEW(41),
    DISPTYPE_SUPPORT_SHEET(42),
    DISPTYPE_MDED_SHEET(43),
    DISPTYPE_TRANSPLANT_DETAILDOC(44),
    DISPTYPE_TRANSPLANT_FORM(45),
    DISPTYPE_TRANSPLANT_SEARCH_RESULT(46),
    DISPTYPE_TRANSPLANT_MASTER(48),
    DISPTYPE_DOC_FILE(49),
    DISPTYPE_WEC_PAT_LIST(50),
    DISPTYPE_WEC_PAT_REPORTLIST(51),
    DISPTYPE_WEC_PAT_ORDERLIST(52),
    DISPTYPE_WEC_PAT_TRAFULIST(53),
    DISPTYPE_WEC_SEARCH_RESULT(54),
    DISPTYPE_WEC_INDEX(55),
    DISPTYPE_WEC_INDEX_TRAFU(56),
    DISPTYPE_WEC_CAVE(57),
    DISPTYPE_WEC_ORDER_REPORT_RELATION_INDEX(58),
    DISPTYPE_WEC_EXTERNAL_ITEM(59),
    DISPTYPE_CONF_DOC_FORM(61),
    DISPTYPE_CONF_REG_FORM(63),
    DISPTYPE_TASK_INDEX(64),
    DISPTYPE_DESK_PERSON_INFO(65),
    DISPTYPE_WEBPORTAL(66),
    DISPTYPE_BATCH_FORM(68),
    DISPTYPE_DESK_PATLIST(70),
    DISPTYPE_DESK_PHYSLIST(71),
    DISPTYPE_REPORTCENTER_VIEW(72),
    DISPTYPE_FORMEDITTOOL_LAYOUT(73),
    DISPTYPE_FORMEDITTOOL_STYLE(74),
    DISPTYPE_FORMEDITTOOL_GROUP(75),
    DISPTYPE_FORMEDITTOOL_DATA(76),
    DISPTYPE_FORMEDITTOOL_FUNCTION(77),
    DISPTYPE_FORMEDITTOOL_RULE(78),
    DISPTYPE_DESK_SERIESPRINT(80),
    DISPTYPE_DESK_SURVEY(81),
    DISPTYPE_DESK_PEDIGREE(83),
    DISPTYPE_HTML(84),
    DISPTYPE_BATCH_HISTORY_EDIT(85),
    DISPTYPE_BIOMAT_CONTAINER_LAYOUT_EDIT(86),
    DISPTYPE_IXCONNECT(87),
    DISPTYPE_BIOMAT_CONTAINERTYPE_EDIT(88),
    DISPTYPE_BIOMAT_CONTAINER_EDIT(89),
    DISPTYPE_BIOMAT_FORM(90),
    DISPTYPE_HUMANPREPARATION_INVENTORY(91),
    DISPTYPE_HUMANPREPARATION_CHECKOUT(92),
    DISPTYPE_HUMANPREPARATION_SEARCH(93),
    DISPTYPE_CLEARING(94),
    DISPTYPE_REPORTCENTER_SIGNATURE(95),
    DISPTYPE_CUMREP_LIMITED(97),
    DISPTYPE_WEC_PAT_CUMREP_LIMITED(98),
    DISPTYPE_PHYSDOC_ORDER(99),
    DISPTYPE_SESSIONLIST(103),
    DISPTYPE_PROCESS_LIST(104),
    DISPTYPE_PROCESS_DETAIL(105),
    DISPTYPE_PAT_TREATMENTACCESS(111),
    DISPTYPE_PROCESS_CHILDREN(112),
    DISPTYPE_USERMANAGEMENT_GENERAL(113),
    DISPTYPE_REPORTCENTER_SCAN(114),
    DISPTYPE_WEC_PAT_CUMREP_MIBI_STRUCTURED(115),
    DISPTYPE_PAT_CONSENT(116);

    private final int dbValue;

    IxtDisplayType(int dbValue) {
        this.dbValue = dbValue;
    }

    public int getDbValue() {
        return dbValue;
    }

    public static IxtDisplayType fromDbValue(int dbValue) {
        for (IxtDisplayType displayType : values()) {
            if (displayType.dbValue == dbValue) {
                return displayType;
            }
        }
        throw new IllegalArgumentException("Unbekannter IxtDisplayType-Datenbankwert: " + dbValue);
    }
}
